FROM node:12-alpine

RUN mkdir /apidoc
WORKDIR /apidoc

COPY ./src ./src
COPY ./package.json ./package.json 
COPY ./apidoc.json ./apidoc.json 

RUN npm install apidoc serve && npm run apidoc

CMD npm run apidoc:serve
